export const MONGO_URI = 'MONGO_URI';
export const SESSION_STORE = 'SESSION_STORE';
export const PORT = 'PORT';
export const EXTERNAL_URL = 'EXTERNAL_URL';
export const REDIS_HOST = 'REDIS_HOST';
export const REDIS_PORT = 'REDIS_PORT';
export const REDIS_PASSWORD = 'REDIS_PASSWORD';
export const REDIS_DB = 'REDIS_DB';

export const PLAYLIST_ID = 'PLAYLIST_ID';
export const NETEASE_PHONE = 'NETEASE_PHONE';
export const NETEASE_PASSWORD = 'NETEASE_PASSWORD';
export const NETEASE_COUNTRY_CODE = 'NETEASE_COUNTRY_CODE';
export const SING_USERNAME = 'SING_USERNAME';
export const SING_PASSWORD = 'SING_PASSWORD';

export const MAILER_HOST = 'MAILER_HOST';
export const MAILER_PORT = 'MAILER_PORT';
export const MAILER_SECURE = 'MAILER_SECURE';
export const MAILER_USER = 'MAILER_USER';
export const MAILER_PASS = 'MAILER_PASS';
export const MAILER_NAME = 'MAILER_NAME';

export const ALI_ACCESS_KEY = 'ALI_ACCESS_KEY';
export const ALI_SECRET_KEY = 'ALI_SECRET_KEY';
export const ALI_REGION = 'ALI_REGION';
export const ALI_BUCKET = 'ALI_BUCKET';
export const UPLOAD_FOLDERS = 'UPLOAD_FOLDERS';

export const TENCENT_SECRET_ID = 'TENCENT_SECRET_ID';
export const TENCENT_SECRET_KEY = 'TENCENT_SECRET_KEY';
export const CAPTCHA_APP_ID = 'CAPTCHA_APP_ID';
export const CAPTCHA_SECRET_KEY = 'CAPTCHA_SECRET_KEY';
